# Generated by Django 5.2.5 on 2025-08-08 15:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('dias_plazo', models.PositiveSmallIntegerField(default=7)),
                ('tarifa_retraso', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=8)),
                ('multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='libros.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='usuarios.usuario')),
            ],
            options={
                'indexes': [models.Index(fields=['usuario', 'fecha_prestamo'], name='prestamos_p_usuario_25435b_idx'), models.Index(fields=['libro', 'fecha_prestamo'], name='prestamos_p_libro_i_0d15c4_idx')],
            },
        ),
    ]
