# Generated by Django 5.2.5 on 2025-08-08 19:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
        ('prestamos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='prestamo',
            name='prestamos_p_usuario_25435b_idx',
        ),
        migrations.RemoveIndex(
            model_name='prestamo',
            name='prestamos_p_libro_i_0d15c4_idx',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='multa',
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='dias_plazo',
            field=models.PositiveSmallIntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='tarifa_retraso',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
    ]
