# Generated by Django 5.2.5 on 2025-08-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('isbn', models.CharField(db_index=True, max_length=13, unique=True)),
                ('ejemplares_totales', models.PositiveIntegerField(default=1)),
                ('ejemplares_disponibles', models.PositiveIntegerField(default=1)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('ejemplares_totales__gte', 0)), name='libro_totales_gte_0'), models.CheckConstraint(condition=models.Q(('ejemplares_disponibles__gte', 0)), name='libro_disp_gte_0')],
            },
        ),
    ]
