# Generated by Django 5.2.5 on 2025-08-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True)),
                ('max_prestamos', models.PositiveIntegerField(default=3)),
            ],
        ),
    ]
